#!/bin/bash

# Self-Hosted GitHub Actions Runner Setup for ATOM-SG
# This script sets up a runner on your local machine

echo "=========================================="
echo "GitHub Actions Self-Hosted Runner Setup"
echo "=========================================="
echo ""
echo "Step 1: Get Registration Token"
echo "--------------------------------"
echo "1. Go to: https://github.com/seanfzc/atom-sg/settings/actions/runners"
echo "2. Click 'New self-hosted runner'"
echo "3. Select macOS (Apple Silicon)"
echo "4. Copy the registration token (looks like: AAAAAAAABBBBBBBBBBCCCCCC)"
echo ""
echo "Step 2: Configure the Runner"
echo "-----------------------------"
echo "Run these commands:"
echo ""
echo "cd ~/actions-runner"
echo "./config.sh --url https://github.com/seanfzc/atom-sg --token YOUR_TOKEN"
echo ""
echo "Step 3: Start the Runner"
echo "------------------------"
echo "./run.sh"
echo ""
echo "=========================================="
echo "IMPORTANT: Keep the runner running!"
echo "=========================================="
echo ""
echo "The runner will:"
echo "  - Listen for GitHub Actions jobs"
echo "  - Run tests on your local machine"
echo "  - Access your backend at 192.168.2.6"
echo ""
echo "To stop: Press Ctrl+C"
echo "To restart: Run ./run.sh again"
echo ""
