import fs from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';

// Define types based on OpenClaw hook context
interface CompactAfterContext {
  sessionId: string;
  missingSessionKey?: boolean;
  messageCount: number;
  tokenCount: number;
  compactedCount: number;
  summaryLength: number;
  tokensBefore: number;
  tokensAfter: number;
  firstKeptEntryId?: string;
}

interface HookEvent {
  type: string;
  action: string;
  sessionKey: string;
  timestamp: Date;
  messages: string[];
  context: {
    workspaceDir?: string;
    cfg?: any;
  } & CompactAfterContext;
}

const handler = async (event: HookEvent) => {
  // Only handle session:compact:after
  if (event.type !== 'session' || event.action !== 'compact:after') {
    return;
  }

  try {
    const {
      sessionId,
      messageCount,
      tokenCount,
      compactedCount,
      summaryLength,
      tokensBefore,
      tokensAfter,
      firstKeptEntryId,
    } = event.context;

    const workspaceDir = event.context.workspaceDir || process.env.OPENCLAW_WORKSPACE;
    if (!workspaceDir) {
      console.error('[compaction-to-second-brain] No workspace directory found');
      return;
    }

    // Path to second brain raw folder
    const secondBrainRawDir = path.join(workspaceDir, 'second-brain-simple', 'raw', 'conversations');
    
    // Create directory if it doesn't exist
    await fs.mkdir(secondBrainRawDir, { recursive: true });

    // Generate filename with timestamp
    const now = new Date();
    const dateStr = now.toISOString().split('T')[0]; // YYYY-MM-DD
    const timeStr = now.toISOString().split('T')[1].split('.')[0].replace(/:/g, '-'); // HH-MM-SS
    const filename = `compaction-${dateStr}-${timeStr}.md`;
    const filePath = path.join(secondBrainRawDir, filename);

    // Create markdown content
    const content = `# Conversation Compaction Summary
*Generated ${now.toISOString()}*

## Metadata
- **Session ID:** ${sessionId}
- **Session Key:** ${event.sessionKey}
- **Compacted At:** ${now.toLocaleString()}
- **Messages Before Compaction:** ${messageCount + compactedCount}
- **Messages After Compaction:** ${messageCount}
- **Messages Compacted:** ${compactedCount}
- **Tokens Before:** ${tokensBefore}
- **Tokens After:** ${tokensAfter}
- **Summary Length:** ${summaryLength} characters
- **First Kept Entry ID:** ${firstKeptEntryId || 'N/A'}

## What Was Compacted
Older parts of the conversation were summarized to stay within model context limits. The summary preserves key decisions, insights, and context while reducing token usage.

## Education Transformation Lens
### Game-Based Learning Potential
- **Concept Extraction:** What core concepts were discussed that could be turned into learning games?
- **Age Adaptation:** How could these concepts be simplified for 6-year-old vs 11-year-old?
- **Skill Development:** Which future skills (critical thinking, problem-solving, systems thinking) were exercised in this conversation?
- **Psychology Integration:** How could child psychology principles make these concepts more engaging?

### Conversation Themes for Learning Games
1. **Theme 1:** [Identify a key theme from the conversation]
   - Game mechanic idea: [Brief game concept]
   - Learning objective: [What would children learn?]

2. **Theme 2:** [Another theme]
   - Game mechanic idea: [Brief game concept]
   - Learning objective: [What would children learn?]

## Raw Data (for reference)
\`\`\`json
${JSON.stringify({
  sessionId,
  sessionKey: event.sessionKey,
  timestamp: now.toISOString(),
  metrics: {
    tokensBefore,
    tokensAfter,
    tokenReduction: tokensBefore - tokensAfter,
    messagesBefore: messageCount + compactedCount,
    messagesAfter: messageCount,
    compactedCount,
    summaryLength,
  },
  firstKeptEntryId,
}, null, 2)}
\`\`\`

## Next Steps
- Review this summary for insights worth adding to the wiki
- Identify patterns across multiple compactions (what conversations tend to grow long?)
- Design learning games based on frequently discussed concepts
- Update education-development framework with new insights

---
*This file was automatically generated by the compaction-to-second-brain hook.*`;

    await fs.writeFile(filePath, content, 'utf8');
    
    console.log(`[compaction-to-second-brain] Saved compaction summary to ${filePath}`);
    
    // Optional: Add a message to the user (but compaction already shows a notice)
    // event.messages.push(`Compaction summary saved to second brain: ${filename}`);
    
  } catch (error) {
    console.error('[compaction-to-second-brain] Error:', error);
  }
};

export default handler;